//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompOption
    {
        public long Id { get; set; }
        public long OptionId { get; set; }
        public long ComponentId { get; set; }
    }
}
