//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public long Id { get; set; }
        public int BuildId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double CallValue { get; set; }
        public double ValueToSystem { get; set; }
        public double CostToBuild { get; set; }
        public double ValueToCostRatio { get; set; }
        public double Volatility { get; set; }
        public int DurationDays { get; set; }
        public bool Complete { get; set; }
    }
}
